spring:
    datasource:
        url: jdbc:mysql://localhost:3306/acortador_url?createDatabaseIfNotExist=true
        username: prueba
        password: prueba
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true

    application:
        name: acortadorUrlBackEnd
app:
    url:
        shortener:
            domain: http://localhost:4200
            URL_PATH: /obtenerUrlOriginal/
            REDIRECT_URL_PATH: /acortar